import { createContext, useContext, useState, useEffect, useCallback } from 'react';

const translations = {
  ar: {
    // Nav
    home: 'الرئيسية',
    clinics: 'التخصصات',
    book: 'حجز موعد',
    queue: 'الطابور الحي',
    assistant: 'المساعد الذكي',
    records: 'سجلاتي الطبية',
    // Theme
    lightMode: 'وضع فاتح',
    darkMode: 'وضع داكن',
    logout: 'تسجيل خروج',
    // Home
    goodMorning: 'صباح الخير',
    goodEvening: 'مساء الخير',
    heroSub: 'كل مواعيدك وطابورك وسجلك الطبي في واجهة واحدة.',
    bookNow: 'احجز الآن',
    askAssistant: 'اسأل المساعد',
    servingNow: 'يُخدم الآن',
    waiting: 'في الانتظار',
    avgService: 'متوسط الخدمة ٨ دقائق',
    availableSpecs: 'التخصصات المتاحة',
    doctors: 'أطباء',
    quickActions: 'اختصارات سريعة',
    browseClinics: 'التخصصات والأطباء',
    bookAppointment: 'حجز موعد',
    liveQueue: 'الطابور الحي',
    smartAssistant: 'المساعد الذكي',
    myRecords: 'سجلاتي الطبية',
    // Page headers
    homeSub: 'نظرة سريعة على يومك في العيادة',
    clinicsSub: 'اختر التخصص لعرض الأطباء المتاحين',
    bookSub: 'ثلاث خطوات ويصلك رقمك في الطابور',
    queueSub: 'يتحدّث تلقائياً كل ١٠ ثوانٍ',
    chatSub: 'اسأل عن أعراضك أو التخصص المناسب',
    recordsSub: 'أدويتك، زياراتك، تحاليلك، ومستنداتك',
    admin: 'إدارة العيادة',
    adminSub: 'أطباء، طابور، وإعدادات',
    // Booking
    step1: 'التخصص والطبيب',
    step2: 'بياناتك',
    step3: 'تأكيد',
    chooseClinic: 'اختار التخصص',
    chooseDoctor: 'اختار الطبيب من تخصص',
    backToClinics: 'رجوع للتخصصات',
    bookWith: 'احجز مع د.',
    yourName: 'اسمك الكامل',
    phone: 'رقم التليفون',
    next: 'التالي',
    change: 'غيّر',
    confirm: 'تأكيد الحجز',
    bookingSuccess: 'تم الحجز بنجاح!',
    queueNumber: 'رقمك في الطابور',
    estimatedWait: 'وقت الانتظار المتوقع',
    minutes: 'دقيقة',
    goToQueue: 'تابع في الطابور',
    // Queue
    refreshIn: 'التحديث بعد',
    seconds: 'ث',
    refreshNow: 'تحديث الآن',
    liveUpdate: 'تحديث مباشر',
    number: 'الرقم',
    patient: 'المريض',
    doctor: 'الطبيب',
    status: 'الحالة',
    inClinic: 'داخل العيادة',
    // Chat
    aiAssistant: 'المساعد الطبي الذكي',
    onlineNow: 'متصل الآن',
    newChat: 'محادثة جديدة',
    chatHistory: 'المحادثات السابقة',
    typeQuestion: 'اكتب سؤالك الطبي...',
    disclaimer: 'هذا إرشاد مبدئي ولا يُعد تشخيصاً طبياً. في الحالات الطارئة توجّه للطوارئ فوراً.',
    // Records
    medications: 'الأدوية',
    visits: 'الزيارات',
    documents: 'المستندات',
    currentMeds: 'الأدوية الحالية',
    addMed: 'إضافة دواء',
    addMedSub: 'أضف دواءً تتناوله حالياً ليظهر في سجلك.',
    medName: 'اسم الدواء',
    dosage: 'الجرعة — مثال: 500 ملغم',
    frequency: 'التكرار — مثال: مرتين يومياً',
    frequencyNum: 'عدد مرات التناول يومياً (رقم)',
    saveMed: 'حفظ الدواء',
    noMeds: 'مفيش أدوية مسجّلة',
    noVisits: 'مفيش زيارات مسجّلة',
    dragFiles: 'اسحب مستنداتك هنا',
    dragFilesSub: 'تقارير، تحاليل، أو أشعة — نضيفها إلى سجلك مباشرة.',
    chooseFile: 'اختيار ملف',
    uploadedDocs: 'المستندات المرفوعة',
    uploadHint: 'ارفع ملفات وهتظهر هنا.',
    delete: 'حذف',
    // Auth
    welcome: 'أهلاً بعودتك',
    loginSub: 'سجّل دخولك للوصول إلى مواعيدك وسجلك الطبي.',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    login: 'تسجيل الدخول',
    loggingIn: 'جاري الدخول...',
    noAccount: 'مش عندك حساب؟',
    registerHere: 'سجّل هنا',
    createAccount: 'أنشئ حسابك',
    registerSub: 'سجّل عشان تقدر تحجز وتتابع',
    fullName: 'الاسم الكامل',
    phoneNumber: 'رقم الجوال',
    register: 'حساب جديد',
    registering: 'جاري التسجيل...',
    haveAccount: 'عندك حساب؟',
    loginHere: 'ادخل هنا',
    accountCreated: 'تم إنشاء حسابك بنجاح',
    redirecting: 'هيتم تحويلك لصفحة الدخول...',
    secureData: 'بيانات المرضى محفوظة ومشفّرة داخل النظام.',
    user: 'مستخدم',
    specs: 'تخصصات',
    clinic: 'تخصص',
    available: 'متاح',
    whichSpec: 'أي تخصص تحتاج زيارته اليوم؟',
    patientName: 'اسم المريض',
    mobile: 'رقم الجوال',
    confirmBooking: 'تأكيد الحجز',
    clinicLabel: 'التخصص',
    doctorLabel: 'الطبيب',
    nameLabel: 'الاسم',
    mobileLabel: 'الجوال',
    appointmentLabel: 'الموعد',
    todayNext: 'اليوم — أول رقم متاح',
    confirming: 'جاري الحجز...',
    bookingConfirmed: 'تم تأكيد حجزك',
    newBooking: 'حجز جديد',
    approxMin: 'دقيقة تقريباً',
    thinking: 'بيفكّر...',
    noClinics: 'مفيش تخصصات متاحة حالياً',
    noChats: 'لا توجد محادثات سابقة',
    deleteAll: 'مسح الكل',
    more: 'المزيد',
    chats: 'المحادثات',
    visitDetails: 'تفاصيل الزيارة',
    diagnosisLabel: 'التشخيص',
    doctorNotes: 'ملاحظات الطبيب',
    fileTypes: 'PDF أو JPG أو PNG — حتى 10 ميجابايت',
    uploading: 'جاري الرفع...',
    saving: 'جاري الحفظ...',
    accountType: 'نوع الحساب',
    accountTypeQ: 'هتسجّل كإيه؟',
    patientRole: 'مريض',
    patientRoleDesc: 'احجز مواعيد، تابع الطابور، واحتفظ بسجلك الطبي.',
    clinicRole: 'عيادة',
    clinicRoleDesc: 'أضف أطباء، تحكّم في الطابور، وأدر عيادتك بالكامل.',
    changeRole: 'غيّر نوع الحساب',
    clinicRegister: 'تسجيل عيادة',
    clinicRegisterSub: 'سجّل عيادتك وابدأ إضافة الأطباء',
    clinicNameLabel: 'اسم العيادة / المسؤول',
    contactNumber: 'رقم التواصل',
    addDoctor: 'إضافة طبيب',
    registered: 'مسجّل',
    noDoctors: 'مفيش أطباء مسجّلين. أضف أول طبيب!',
    noQueue: 'مفيش حد في الطابور حالياً',
    served: 'تم خدمتهم',
    total: 'الإجمالي',
    waitingList: 'قائمة الانتظار',
    markDone: 'تم',
    newDoctor: 'طبيب جديد',
    doctorNamePh: 'د. أحمد محمد',
    specPh: 'عيون / أسنان / باطنة / جلدية',
    bioPh: 'خبرة 10 سنوات...',
    bio: 'نبذة (اختياري)',
    save: 'حفظ',
    cancel: 'إلغاء',
    back: 'رجوع',
    specLabel: 'التخصص',
    // Chat extra
    suggestion1: 'عندي صداع مستمر من يومين',
    suggestion2: 'ألم في الأسنان عند الأكل',
    suggestion3: 'حبوب وحكة في الوجه',
    suggestion4: 'كيف أحجز موعداً؟',
    chatWelcome: 'أهلاً بك في المساعد الطبي الذكي.\nاوصف لي الأعراض التي تشعر بها وسأرشدك للتخصص المناسب وخطوة الحجز التالية.',
    chatWelcomeNew: 'أهلاً! محادثة جديدة. إزاي أساعدك؟',
    chatErrorReply: 'مقدرتش أرد دلوقتي، جرّب تاني.',
    chatErrorTimeout: 'الرد بياخد وقت أطول من اللازم. جرّب تاني كمان شوية.',
    chatErrorConnection: 'في مشكلة في الاتصال بالنظام. جرّب تاني كمان شوية.',
    // Queue extra
    loading: 'جاري التحميل...',
    yourBooking: 'حجزك في الطابور',
    aheadOfYou: 'أمامك',
    patientsAhead: 'مريض',
    expectedWait: 'الانتظار المتوقع',
    minuteWord: 'دقيقة',
    emptyQueue: 'مفيش حد في الطابور حالياً',
    doneStatus: 'انتهى',
    inWaiting: 'في الانتظار',
    you: 'أنت',
    // Doctors extra
    allClinics: 'كل التخصصات',
    noDoctorsInClinic: 'مفيش أطباء في التخصص ده حالياً',
    clinicPrefix: 'تخصص',
    oneDoctor: 'طبيب',
    // Login extra
    brandDesc: 'حجز المواعيد، الطابور الحي، والسجل الطبي — كل شيء في مكان واحد.',
    feature1: 'احجز مع طبيبك في أقل من دقيقة',
    feature2: 'تابع رقمك في الطابور لحظة بلحظة',
    feature3: 'سجلك الطبي وأدويتك دائماً معك',
    loginError: 'الإيميل أو الباسورد غلط',
    // Register extra
    adminBrandDesc: 'سجّل عيادتك وابدأ إدارة الأطباء والمواعيد.',
    patientBrandDesc: 'دقيقة واحدة وتصبح جاهزاً لحجز أول موعد.',
    minChars: '8 حروف على الأقل',
    registerError: 'في مشكلة — جرّب تاني',
    clinicPh: 'عيادة النور',
    // ClinicAdmin extra
    doctorsTab: 'الأطباء',
    queueTab: 'الطابور',
    doctorCount: 'طبيب مسجّل',
    doctorAdded: 'تمت إضافة الطبيب',
    doctorAddError: 'مقدرتش أضيف الطبيب — جرّب تاني',
    patientServed: 'تم خدمة المريض',
    errorOccurred: 'حصلت مشكلة',
    doctorNameLabel: 'اسم الطبيب',
    // Records toasts
    medDeleted: 'تم حذف الدواء',
    medDeleteError: 'مقدرتش أحذف الدوا — جرّب تاني',
    medRequired: 'اسم الدواء والجرعة والتكرار مطلوبين',
    remindersProgress: 'الفترات المحددة',
    allRemindersSet: 'تم تحديد كل الفترات',
    medAdded: 'أضفنا الدواء إلى سجلك',
    medAddError: 'مقدرتش أضيف الدوا — جرّب تاني',
    filesUploaded: 'ملف تم رفعه',
    uploadError: 'حصلت مشكلة في الرفع',
    uploadErrorGeneric: 'حصلت مشكلة — جرّب تاني',
    visitLabel: 'زيارة',
    // Booking extra
    phoneError: 'رقم التليفون لازم 11 رقم يبدأ بـ 01',
    bookingError: 'حصلت مشكلة — جرّب تاني',
    bookingSuccessToast: 'تم الحجز بنجاح!',
    nameSpecRequired: 'الاسم والتخصص مطلوبين',
    // Admin extra
    usersTab: 'المستخدمين',
    logsTab: 'سجل العمليات',
    usersCount: 'مستخدم',
    noUsers: 'مفيش مستخدمين',
    userDeleted: 'تم حذف المستخدم',
    deleteUser: 'حذف مستخدم',
    inactive: 'معطّل',
    auditLogs: 'سجل العمليات',
    noLogs: 'مفيش عمليات مسجّلة',
    avgWait: 'متوسط الخدمة',
    saved: 'تم الحفظ',
    noFiles: 'مفيش ملفات مرفوعة',
    fileName: 'اسم الملف',
    uploadDate: 'تاريخ الرفع',
    fileSize: 'الحجم',
    chiefComplaint: 'الشكوى الرئيسية',
    diagnosis: 'التشخيص',
    followUp: 'المتابعة',
    visitDate: 'تاريخ الزيارة',
    addNote: 'إضافة ملاحظة',
    noteText: 'نص الملاحظة',
    noteSaved: 'تم حفظ الملاحظة',
    patientNotes: 'ملاحظات المريض',
    noNotes: 'مفيش ملاحظات',
    editMed: 'تعديل الدواء',
    endDate: 'تاريخ الانتهاء',
    active: 'فعّال',
    medUpdated: 'تم تعديل الدواء',
    prescribedBy: 'وصفه د.',
    prescribeMed: 'كتابة دواء',
    prescribeAdd: 'إضافة الدواء للمريض',
    prescribedNow: 'الأدوية المكتوبة',
    medPrescribed: 'تم كتابة الدواء للمريض',
    manageMedsHint: 'لإدارة الأدوية والتذكيرات، اذهب لصفحة "أدويتي"',
    daily: 'يومياً',
    timesDaily: 'مرات يومياً',
    reminders: 'التذكيرات',
    addReminder: 'إضافة تذكير',
    reminderTime: 'وقت التذكير',
    reminderSaved: 'تم حفظ التذكير',
    queueFor: 'طابور',
    myMedications: 'أدويتي',
    medPageSub: 'نظّم أدويتك ومواعيدها واحصل على تذكير قبل كل جرعة',
    addNewMed: 'إضافة دواء جديد',
    medTiming: 'مواعيد الدواء',
    choosePeriod: 'اختر الفترة',
    beforeBreakfast: 'قبل الفطار',
    onEmptyStomach: 'عالريق',
    afterBreakfast: 'بعد الفطار',
    beforeLunch: 'قبل الغداء',
    afterLunch: 'بعد الغداء',
    beforeDinner: 'قبل العشاء',
    afterDinner: 'بعد العشاء',
    beforeSleep: 'قبل النوم',
    periodTime: 'الوقت',
    addPeriod: 'إضافة',
    currentReminders: 'التذكيرات الحالية',
    noReminders: 'مفيش تذكيرات — أضف مواعيد لأدويتك',
    telegramLinked: 'تليجرام مرتبط',
    telegramNotLinked: 'تليجرام مش مرتبط',
    linkTelegram: 'ربط تليجرام',
    telegramId: 'Telegram Chat ID',
    telegramSaved: 'تم ربط تليجرام',
    startWithBot: 'ابدأ مع البوت',
    waitingForTelegram: 'في انتظار الربط... افتح البوت واضغط Start',
    orEnterManually: 'أو أدخل الـ Chat ID يدوياً:',
    reminderWillSend: 'هيتبعتلك تذكير قبل كل جرعة بـ 5 دقايق',
    removePeriod: 'حذف',
  },
  en: {
    // Nav
    home: 'Home',
    clinics: 'Specializations',
    book: 'Book',
    queue: 'Live Queue',
    assistant: 'AI Assistant',
    records: 'My Records',
    // Theme
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    logout: 'Log out',
    // Home
    goodMorning: 'Good morning',
    goodEvening: 'Good evening',
    heroSub: 'All your appointments, queue, and records in one place.',
    bookNow: 'Book Now',
    askAssistant: 'Ask Assistant',
    servingNow: 'Serving Now',
    waiting: 'Waiting',
    avgService: 'Avg. service 8 min',
    availableSpecs: 'Available Specializations',
    doctors: 'doctors',
    quickActions: 'Quick Actions',
    browseClinics: 'Specializations & Doctors',
    bookAppointment: 'Book Appointment',
    liveQueue: 'Live Queue',
    smartAssistant: 'AI Assistant',
    myRecords: 'My Records',
    // Page headers
    homeSub: 'A quick look at your day at the clinic',
    clinicsSub: 'Choose a specialization to see available doctors',
    bookSub: 'Three steps and you get your queue number',
    queueSub: 'Auto-refreshes every 10 seconds',
    chatSub: 'Ask about symptoms or the right specialization',
    recordsSub: 'Your medications, visits, tests, and documents',
    admin: 'Clinic Admin',
    adminSub: 'Doctors, queue, and settings',
    // Booking
    step1: 'Specialization & Doctor',
    step2: 'Your Details',
    step3: 'Confirm',
    chooseClinic: 'Choose Specialization',
    chooseDoctor: 'Choose doctor from',
    backToClinics: 'Back to specializations',
    bookWith: 'Book with Dr.',
    yourName: 'Your Full Name',
    phone: 'Phone Number',
    next: 'Next',
    change: 'Change',
    confirm: 'Confirm Booking',
    bookingSuccess: 'Booking Confirmed!',
    queueNumber: 'Your Queue Number',
    estimatedWait: 'Estimated Wait Time',
    minutes: 'min',
    goToQueue: 'Go to Queue',
    // Queue
    refreshIn: 'Refreshing in',
    seconds: 's',
    refreshNow: 'Refresh now',
    liveUpdate: 'Live Update',
    number: '#',
    patient: 'Patient',
    doctor: 'Doctor',
    status: 'Status',
    inClinic: 'In Clinic',
    // Chat
    aiAssistant: 'AI Medical Assistant',
    onlineNow: 'Online now',
    newChat: 'New Chat',
    chatHistory: 'Previous Chats',
    typeQuestion: 'Type your medical question...',
    disclaimer: 'This is preliminary guidance, not a medical diagnosis. In emergencies, go to ER immediately.',
    // Records
    medications: 'Medications',
    visits: 'Visits',
    documents: 'Documents',
    currentMeds: 'Current Medications',
    addMed: 'Add Medication',
    addMedSub: 'Add a medication you currently take.',
    medName: 'Medication Name',
    dosage: 'Dosage — e.g. 500mg',
    frequency: 'Frequency — e.g. twice daily',
    frequencyNum: 'Times per day (number)',
    saveMed: 'Save Medication',
    noMeds: 'No medications recorded',
    noVisits: 'No visits recorded',
    dragFiles: 'Drag your files here',
    dragFilesSub: 'Reports, tests, or X-rays — added to your record.',
    chooseFile: 'Choose File',
    uploadedDocs: 'Uploaded Documents',
    uploadHint: 'Upload files and they will appear here.',
    delete: 'Delete',
    // Auth
    welcome: 'Welcome Back',
    loginSub: 'Sign in to access your appointments and records.',
    email: 'Email',
    password: 'Password',
    login: 'Sign In',
    loggingIn: 'Signing in...',
    noAccount: "Don't have an account?",
    registerHere: 'Register here',
    createAccount: 'Create Account',
    registerSub: 'Register to book and track appointments',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    register: 'Create Account',
    registering: 'Creating...',
    haveAccount: 'Have an account?',
    loginHere: 'Sign in here',
    accountCreated: 'Account created successfully',
    redirecting: 'Redirecting to login...',
    secureData: 'Patient data is stored securely and encrypted.',
    user: 'User',
    specs: 'specializations',
    clinic: 'specialization',
    available: 'Available',
    whichSpec: 'Which specialization do you need today?',
    patientName: 'Patient Name',
    mobile: 'Phone Number',
    confirmBooking: 'Confirm Booking',
    clinicLabel: 'Specialization',
    doctorLabel: 'Doctor',
    nameLabel: 'Name',
    mobileLabel: 'Phone',
    appointmentLabel: 'Appointment',
    todayNext: 'Today — next available',
    confirming: 'Booking...',
    bookingConfirmed: 'Your booking is confirmed',
    newBooking: 'New Booking',
    approxMin: 'minutes approx.',
    thinking: 'Thinking...',
    noClinics: 'No specializations available right now',
    noChats: 'No previous chats',
    deleteAll: 'Clear all',
    more: 'More',
    chats: 'Chats',
    visitDetails: 'Visit Details',
    diagnosisLabel: 'Diagnosis',
    doctorNotes: 'Doctor Notes',
    fileTypes: 'PDF, JPG or PNG — up to 10MB',
    uploading: 'Uploading...',
    saving: 'Saving...',
    accountType: 'Account Type',
    accountTypeQ: 'What are you registering as?',
    patientRole: 'Patient',
    patientRoleDesc: 'Book appointments, track queue, and keep your records.',
    clinicRole: 'Clinic',
    clinicRoleDesc: 'Add doctors, manage queue, and run your clinic.',
    changeRole: 'Change account type',
    clinicRegister: 'Register Clinic',
    clinicRegisterSub: 'Register your clinic and start adding doctors',
    clinicNameLabel: 'Clinic / Admin Name',
    contactNumber: 'Contact Number',
    addDoctor: 'Add Doctor',
    registered: 'registered',
    noDoctors: 'No doctors registered. Add your first doctor!',
    noQueue: 'No one in the queue right now',
    served: 'Served',
    total: 'Total',
    waitingList: 'Waiting List',
    markDone: 'Done',
    newDoctor: 'New Doctor',
    doctorNamePh: 'Dr. Ahmed Mohamed',
    specPh: 'Eye / Dental / Internal / Derma',
    bioPh: '10 years experience...',
    bio: 'Bio (optional)',
    save: 'Save',
    cancel: 'Cancel',
    back: 'Back',
    specLabel: 'Specialization',
    // Chat extra
    suggestion1: 'I have a persistent headache for 2 days',
    suggestion2: 'Tooth pain when eating',
    suggestion3: 'Bumps and itching on my face',
    suggestion4: 'How do I book an appointment?',
    chatWelcome: 'Welcome to the AI Medical Assistant.\nDescribe your symptoms and I\'ll guide you to the right specialization and next booking step.',
    chatWelcomeNew: 'Hello! New conversation. How can I help you?',
    chatErrorReply: 'Couldn\'t respond right now, try again.',
    chatErrorTimeout: 'Response is taking too long. Try again shortly.',
    chatErrorConnection: 'Connection issue. Try again shortly.',
    // Queue extra
    loading: 'Loading...',
    yourBooking: 'Your Queue Position',
    aheadOfYou: 'Ahead of you',
    patientsAhead: 'patients',
    expectedWait: 'Expected wait',
    minuteWord: 'min',
    emptyQueue: 'No one in the queue right now',
    doneStatus: 'Done',
    inWaiting: 'Waiting',
    you: 'You',
    // Doctors extra
    allClinics: 'All Specializations',
    noDoctorsInClinic: 'No doctors in this specialization right now',
    clinicPrefix: '',
    oneDoctor: 'doctor',
    // Login extra
    brandDesc: 'Appointments, live queue, and medical records — all in one place.',
    feature1: 'Book with your doctor in under a minute',
    feature2: 'Track your queue number in real time',
    feature3: 'Your records and medications always with you',
    loginError: 'Incorrect email or password',
    // Register extra
    adminBrandDesc: 'Register your clinic and start managing doctors and appointments.',
    patientBrandDesc: 'One minute and you\'re ready to book your first appointment.',
    minChars: 'At least 8 characters',
    registerError: 'Something went wrong — try again',
    clinicPh: 'Al Noor Clinic',
    // ClinicAdmin extra
    doctorsTab: 'Doctors',
    queueTab: 'Queue',
    doctorCount: 'doctors registered',
    doctorAdded: 'Doctor added successfully',
    doctorAddError: 'Couldn\'t add doctor — try again',
    patientServed: 'Patient served',
    errorOccurred: 'Something went wrong',
    doctorNameLabel: 'Doctor Name',
    // Records toasts
    medDeleted: 'Medication deleted',
    medDeleteError: 'Couldn\'t delete medication — try again',
    medRequired: 'Name, dosage and frequency are required',
    remindersProgress: 'Periods set',
    allRemindersSet: 'All periods set',
    medAdded: 'Medication added to your record',
    medAddError: 'Couldn\'t add medication — try again',
    filesUploaded: 'file(s) uploaded',
    uploadError: 'Upload failed',
    uploadErrorGeneric: 'Something went wrong — try again',
    visitLabel: 'Visit',
    // Booking extra
    phoneError: 'Phone must be 11 digits starting with 01',
    bookingError: 'Something went wrong — try again',
    bookingSuccessToast: 'Booking confirmed!',
    nameSpecRequired: 'Name and specialization are required',
    // Admin extra
    usersTab: 'Users',
    logsTab: 'Audit Logs',
    usersCount: 'users',
    noUsers: 'No users found',
    userDeleted: 'User deleted',
    deleteUser: 'Delete user',
    inactive: 'Inactive',
    auditLogs: 'Audit Logs',
    noLogs: 'No audit logs yet',
    avgWait: 'Avg. Service',
    saved: 'Saved',
    noFiles: 'No uploaded files',
    fileName: 'File Name',
    uploadDate: 'Upload Date',
    fileSize: 'Size',
    chiefComplaint: 'Chief Complaint',
    diagnosis: 'Diagnosis',
    followUp: 'Follow-up',
    visitDate: 'Visit Date',
    addNote: 'Add Note',
    noteText: 'Note text',
    noteSaved: 'Note saved',
    patientNotes: 'Patient Notes',
    noNotes: 'No notes yet',
    editMed: 'Edit Medication',
    endDate: 'End Date',
    active: 'Active',
    medUpdated: 'Medication updated',
    prescribedBy: 'Prescribed by Dr.',
    prescribeMed: 'Prescribe Medication',
    prescribeAdd: 'Add medication for patient',
    prescribedNow: 'Prescribed medications',
    medPrescribed: 'Medication prescribed to patient',
    manageMedsHint: 'To manage medications & reminders, go to "My Medications"',
    daily: 'daily',
    timesDaily: 'times/day',
    reminders: 'Reminders',
    addReminder: 'Add Reminder',
    reminderTime: 'Reminder Time',
    reminderSaved: 'Reminder saved',
    queueFor: 'Queue for',
    myMedications: 'My Medications',
    medPageSub: 'Manage your medications and get reminders before each dose',
    addNewMed: 'Add New Medication',
    medTiming: 'Medication Schedule',
    choosePeriod: 'Choose Period',
    beforeBreakfast: 'Before Breakfast',
    onEmptyStomach: 'On Empty Stomach',
    afterBreakfast: 'After Breakfast',
    beforeLunch: 'Before Lunch',
    afterLunch: 'After Lunch',
    beforeDinner: 'Before Dinner',
    afterDinner: 'After Dinner',
    beforeSleep: 'Before Sleep',
    periodTime: 'Time',
    addPeriod: 'Add',
    currentReminders: 'Current Reminders',
    noReminders: 'No reminders — add schedules to your medications',
    telegramLinked: 'Telegram linked',
    telegramNotLinked: 'Telegram not linked',
    linkTelegram: 'Link Telegram',
    telegramId: 'Telegram Chat ID',
    telegramSaved: 'Telegram linked',
    startWithBot: 'Start with Bot',
    waitingForTelegram: 'Waiting for link... open the bot and press Start',
    orEnterManually: 'Or enter Chat ID manually:',
    reminderWillSend: 'You will get a reminder 5 minutes before each dose',
    removePeriod: 'Remove',
  },
};

const LangContext = createContext();

export function useLang() { return useContext(LangContext); }

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('clinicon-lang') || 'ar'; }
    catch { return 'ar'; }
  });

  const isRTL = lang === 'ar';

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    try { localStorage.setItem('clinicon-lang', lang); }
    catch {}
  }, [lang, isRTL]);

  const toggle = () => setLang(l => l === 'ar' ? 'en' : 'ar');

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations.ar[key] || key;
  }, [lang]);

  return (
    <LangContext.Provider value={{ lang, isRTL, toggle, t }}>
      {children}
    </LangContext.Provider>
  );
}
